// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8cGycKtXx8N0lkltNfVqjlTUHQBn3BRY',
    appId: '1:512010837881:web:e002b89d9fff67967459a8',
    messagingSenderId: '512010837881',
    projectId: 'ruta-este',
    authDomain: 'ruta-este.firebaseapp.com',
    storageBucket: 'ruta-este.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCINJPmbRmH4Je3_y95roKL95iUurYRcJk',
    appId: '1:512010837881:android:f0ed88c8babbbaa37459a8',
    messagingSenderId: '512010837881',
    projectId: 'ruta-este',
    storageBucket: 'ruta-este.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtmvvDbDbTrohWT3_yEYG2pi2DkfAr-V0',
    appId: '1:512010837881:ios:e81e0674efc2836c7459a8',
    messagingSenderId: '512010837881',
    projectId: 'ruta-este',
    storageBucket: 'ruta-este.firebasestorage.app',
    iosBundleId: 'com.example.rutaEste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtmvvDbDbTrohWT3_yEYG2pi2DkfAr-V0',
    appId: '1:512010837881:ios:e81e0674efc2836c7459a8',
    messagingSenderId: '512010837881',
    projectId: 'ruta-este',
    storageBucket: 'ruta-este.firebasestorage.app',
    iosBundleId: 'com.example.rutaEste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8cGycKtXx8N0lkltNfVqjlTUHQBn3BRY',
    appId: '1:512010837881:web:68156f94d448dd7a7459a8',
    messagingSenderId: '512010837881',
    projectId: 'ruta-este',
    authDomain: 'ruta-este.firebaseapp.com',
    storageBucket: 'ruta-este.firebasestorage.app',
  );
}
